// このファイルは question_transcription.md から生成された自己言語化トレーニング用の質問データです。
// 大カテゴリ(category) x 中カテゴリ(subCategory) x 元の通し番号(order) を保持しています。

export interface Question {
    id: string;
    category: string;
    subCategory: string;
    order: number;
    text: string;
}

export const CATEGORIES = ["未来", "家族・友人", "自己分析", "勉強", "仕事"] as const;

export const QUESTIONS: Question[] = [
    // ===== 未来 =====
    // --- 近い未来 ---
    { id: "future-1", category: "未来", subCategory: "近い未来", order: 1, text: "そもそもなぜ未来を考えるのか？" },
    { id: "future-2", category: "未来", subCategory: "近い未来", order: 2, text: "1年後、どんな人間になっていたいか？" },
    { id: "future-3", category: "未来", subCategory: "近い未来", order: 3, text: "1年後、どんな仕事をしていたいか？" },
    { id: "future-4", category: "未来", subCategory: "近い未来", order: 4, text: "3年後、どんな人間になっていたいか？" },
    { id: "future-5", category: "未来", subCategory: "近い未来", order: 5, text: "3年後、どんな仕事をしていたいか？" },
    { id: "future-6", category: "未来", subCategory: "近い未来", order: 6, text: "実現のために、今するべきことは？" },
    // --- 30代 ---
    { id: "future-7", category: "未来", subCategory: "30代", order: 7, text: "どんな人間になっていたいか？" },
    { id: "future-8", category: "未来", subCategory: "30代", order: 8, text: "どんな仕事をしていたいか？" },
    { id: "future-9", category: "未来", subCategory: "30代", order: 9, text: "どんなポジションについているか？" },
    { id: "future-10", category: "未来", subCategory: "30代", order: 10, text: "年収は？" },
    { id: "future-11", category: "未来", subCategory: "30代", order: 11, text: "どこに住みたいか？" },
    { id: "future-12", category: "未来", subCategory: "30代", order: 12, text: "ワークライフバランスは？" },
    { id: "future-13", category: "未来", subCategory: "30代", order: 13, text: "プライベートは何をしているか？" },
    { id: "future-14", category: "未来", subCategory: "30代", order: 14, text: "どんなことにチャレンジしているか？" },
    { id: "future-15", category: "未来", subCategory: "30代", order: 15, text: "どんな趣味を楽しんでいるか？" },
    { id: "future-16", category: "未来", subCategory: "30代", order: 16, text: "人間関係はどうなっているか？" },
    { id: "future-17", category: "未来", subCategory: "30代", order: 17, text: "家族との関係は？" },
    // --- 40代 ---
    { id: "future-18", category: "未来", subCategory: "40代", order: 18, text: "どんな人間になっていたいか？" },
    { id: "future-19", category: "未来", subCategory: "40代", order: 19, text: "どんな仕事をしていたいか？" },
    { id: "future-20", category: "未来", subCategory: "40代", order: 20, text: "どんなポジションについているか？" },
    { id: "future-21", category: "未来", subCategory: "40代", order: 21, text: "年収は？" },
    { id: "future-22", category: "未来", subCategory: "40代", order: 22, text: "どこに住みたいか？" },
    { id: "future-23", category: "未来", subCategory: "40代", order: 23, text: "ワークライフバランスは？" },
    { id: "future-24", category: "未来", subCategory: "40代", order: 24, text: "プライベートは何をしているか？" },
    { id: "future-25", category: "未来", subCategory: "40代", order: 25, text: "どんなことにチャレンジしているか？" },
    { id: "future-26", category: "未来", subCategory: "40代", order: 26, text: "どんな趣味を楽しんでいるか？" },
    { id: "future-27", category: "未来", subCategory: "40代", order: 27, text: "人間関係はどうなっているか？" },
    { id: "future-28", category: "未来", subCategory: "40代", order: 28, text: "家族との関係は？" },
    // --- 50代 ---
    { id: "future-29", category: "未来", subCategory: "50代", order: 29, text: "どんな人間になっていたいか？" },
    { id: "future-30", category: "未来", subCategory: "50代", order: 30, text: "どんな仕事をしていたいか？" },
    { id: "future-31", category: "未来", subCategory: "50代", order: 31, text: "どんなポジションについているか？" },
    { id: "future-32", category: "未来", subCategory: "50代", order: 32, text: "年収は？" },
    { id: "future-33", category: "未来", subCategory: "50代", order: 33, text: "どこに住みたいか？" },
    { id: "future-34", category: "未来", subCategory: "50代", order: 34, text: "ワークライフバランスは？" },
    { id: "future-35", category: "未来", subCategory: "50代", order: 35, text: "プライベートは何をしているか？" },
    { id: "future-36", category: "未来", subCategory: "50代", order: 36, text: "どんなことにチャレンジしているか？" },
    { id: "future-37", category: "未来", subCategory: "50代", order: 37, text: "どんな趣味を楽しんでいるか？" },
    { id: "future-38", category: "未来", subCategory: "50代", order: 38, text: "人間関係はどうなっているか？" },
    { id: "future-39", category: "未来", subCategory: "50代", order: 39, text: "家族との関係は？" },
    // --- 定年後 ---
    { id: "future-40", category: "未来", subCategory: "定年後", order: 40, text: "どんな人間になっていたいか？" },
    { id: "future-41", category: "未来", subCategory: "定年後", order: 41, text: "仕事は続けるか？" },
    { id: "future-42", category: "未来", subCategory: "定年後", order: 42, text: "どこに住みたいか？" },
    { id: "future-43", category: "未来", subCategory: "定年後", order: 43, text: "どんなことにチャレンジしているか？" },
    { id: "future-44", category: "未来", subCategory: "定年後", order: 44, text: "どんな趣味を楽しんでいるか？" },
    { id: "future-45", category: "未来", subCategory: "定年後", order: 45, text: "人間関係はどうなっているか？" },
    { id: "future-46", category: "未来", subCategory: "定年後", order: 46, text: "家族との関係は？" },
    { id: "future-47", category: "未来", subCategory: "定年後", order: 47, text: "子供に何を遺したいか？" },
    { id: "future-48", category: "未来", subCategory: "定年後", order: 48, text: "パートナーに先立たれたら？" },
    { id: "future-49", category: "未来", subCategory: "定年後", order: 49, text: "死ぬまでに成し遂げたいことは？" },
    { id: "future-50", category: "未来", subCategory: "定年後", order: 50, text: "どうやって最期を迎えるか？" },
    // ===== 家族・友人 =====
    // --- 導入・父親 ---
    { id: "family-1", category: "家族・友人", subCategory: "導入・父親", order: 1, text: "そもそもなぜ家族・友人を知るのか？" },
    { id: "family-2", category: "家族・友人", subCategory: "導入・父親", order: 2, text: "父親のどんなところが好きか？" },
    { id: "family-3", category: "家族・友人", subCategory: "導入・父親", order: 3, text: "父親のどんなところが嫌いか？" },
    { id: "family-4", category: "家族・友人", subCategory: "導入・父親", order: 4, text: "父親と似ているところは？" },
    { id: "family-5", category: "家族・友人", subCategory: "導入・父親", order: 5, text: "父親と正反対なところは？" },
    { id: "family-6", category: "家族・友人", subCategory: "導入・父親", order: 6, text: "父親との一番の思い出は？" },
    { id: "family-7", category: "家族・友人", subCategory: "導入・父親", order: 7, text: "父親と何を話しているときが楽しいか？" },
    // --- 母親 ---
    { id: "family-8", category: "家族・友人", subCategory: "母親", order: 8, text: "母親のどんなところが好きか？" },
    { id: "family-9", category: "家族・友人", subCategory: "母親", order: 9, text: "母親のどんなところが嫌いか？" },
    { id: "family-10", category: "家族・友人", subCategory: "母親", order: 10, text: "母親と似ているところは？" },
    { id: "family-11", category: "家族・友人", subCategory: "母親", order: 11, text: "母親と正反対なところは？" },
    { id: "family-12", category: "家族・友人", subCategory: "母親", order: 12, text: "母親との一番の思い出は？" },
    { id: "family-13", category: "家族・友人", subCategory: "母親", order: 13, text: "母親と何を話しているときが楽しいか？" },
    // --- 兄弟姉妹 ---
    { id: "family-14", category: "家族・友人", subCategory: "兄弟姉妹", order: 14, text: "兄弟姉妹のどんなところが好きか？" },
    { id: "family-15", category: "家族・友人", subCategory: "兄弟姉妹", order: 15, text: "兄弟姉妹のどんなところが嫌いか？" },
    { id: "family-16", category: "家族・友人", subCategory: "兄弟姉妹", order: 16, text: "兄弟姉妹と似ているところは？" },
    { id: "family-17", category: "家族・友人", subCategory: "兄弟姉妹", order: 17, text: "兄弟姉妹と正反対なところは？" },
    { id: "family-18", category: "家族・友人", subCategory: "兄弟姉妹", order: 18, text: "兄弟姉妹との一番の思い出は？" },
    { id: "family-19", category: "家族・友人", subCategory: "兄弟姉妹", order: 19, text: "兄弟姉妹と何を話しているときが楽しいか？" },
    // --- 祖父 ---
    { id: "family-20", category: "家族・友人", subCategory: "祖父", order: 20, text: "祖父のどんなところが好きか？" },
    { id: "family-21", category: "家族・友人", subCategory: "祖父", order: 21, text: "祖父のどんなところが嫌いか？" },
    { id: "family-22", category: "家族・友人", subCategory: "祖父", order: 22, text: "祖父と似ているところは？" },
    { id: "family-23", category: "家族・友人", subCategory: "祖父", order: 23, text: "祖父と正反対なところは？" },
    { id: "family-24", category: "家族・友人", subCategory: "祖父", order: 24, text: "祖父との一番の思い出は？" },
    { id: "family-25", category: "家族・友人", subCategory: "祖父", order: 25, text: "祖父と何を話しているときが楽しいか？" },
    // --- 祖母 ---
    { id: "family-26", category: "家族・友人", subCategory: "祖母", order: 26, text: "祖母のどんなところが好きか？" },
    { id: "family-27", category: "家族・友人", subCategory: "祖母", order: 27, text: "祖母のどんなところが嫌いか？" },
    { id: "family-28", category: "家族・友人", subCategory: "祖母", order: 28, text: "祖母と似ているところは？" },
    { id: "family-29", category: "家族・友人", subCategory: "祖母", order: 29, text: "祖母と正反対なところは？" },
    { id: "family-30", category: "家族・友人", subCategory: "祖母", order: 30, text: "祖母との一番の思い出は？" },
    { id: "family-31", category: "家族・友人", subCategory: "祖母", order: 31, text: "祖母と何を話しているときが楽しいか？" },
    // --- 子供 ---
    { id: "family-32", category: "家族・友人", subCategory: "子供", order: 32, text: "子供のどんなところが好きか？" },
    { id: "family-33", category: "家族・友人", subCategory: "子供", order: 33, text: "子供のどんなところが嫌いか？" },
    { id: "family-34", category: "家族・友人", subCategory: "子供", order: 34, text: "子供と似ているところは？" },
    { id: "family-35", category: "家族・友人", subCategory: "子供", order: 35, text: "子供と正反対なところは？" },
    { id: "family-36", category: "家族・友人", subCategory: "子供", order: 36, text: "子供との一番の思い出は？" },
    { id: "family-37", category: "家族・友人", subCategory: "子供", order: 37, text: "子供と何を話しているときが楽しいか？" },
    // --- 友人 ---
    { id: "family-38", category: "家族・友人", subCategory: "友人", order: 38, text: "友人のどんなところが好きか？" },
    { id: "family-39", category: "家族・友人", subCategory: "友人", order: 39, text: "友人のどんなところが嫌いか？" },
    { id: "family-40", category: "家族・友人", subCategory: "友人", order: 40, text: "友人と似ているところは？" },
    { id: "family-41", category: "家族・友人", subCategory: "友人", order: 41, text: "友人と正反対なところは？" },
    { id: "family-42", category: "家族・友人", subCategory: "友人", order: 42, text: "友人との一番の思い出は？" },
    { id: "family-43", category: "家族・友人", subCategory: "友人", order: 43, text: "友人と何を話しているときが楽しいか？" },
    // --- パートナー ---
    { id: "family-44", category: "家族・友人", subCategory: "パートナー", order: 44, text: "パートナーと似ているところは？" },
    { id: "family-45", category: "家族・友人", subCategory: "パートナー", order: 45, text: "パートナーと正反対なところは？" },
    { id: "family-46", category: "家族・友人", subCategory: "パートナー", order: 46, text: "パートナーとの一番の思い出は？" },
    { id: "family-47", category: "家族・友人", subCategory: "パートナー", order: 47, text: "パートナーと何を話しているときが楽しいか？" },
    // --- ペット ---
    { id: "family-48", category: "家族・友人", subCategory: "ペット", order: 48, text: "なぜペットを飼うか？" },
    { id: "family-49", category: "家族・友人", subCategory: "ペット", order: 49, text: "ペットの何が好きか？" },
    { id: "family-50", category: "家族・友人", subCategory: "ペット", order: 50, text: "ペットの何が嫌いか？" },
    // ===== 自己分析 =====
    // --- 幼少期 ---
    { id: "self-1", category: "自己分析", subCategory: "幼少期", order: 1, text: "そもそもなぜ自己分析をするのか？" },
    { id: "self-2", category: "自己分析", subCategory: "幼少期", order: 2, text: "何をするのが好きだったか？" },
    { id: "self-3", category: "自己分析", subCategory: "幼少期", order: 3, text: "何をするのが嫌いだったか？" },
    { id: "self-4", category: "自己分析", subCategory: "幼少期", order: 4, text: "何が得意だったか？" },
    { id: "self-5", category: "自己分析", subCategory: "幼少期", order: 5, text: "何が苦手だったか？" },
    { id: "self-6", category: "自己分析", subCategory: "幼少期", order: 6, text: "当時の夢は？" },
    { id: "self-7", category: "自己分析", subCategory: "幼少期", order: 7, text: "どんな友人が多かった？" },
    { id: "self-8", category: "自己分析", subCategory: "幼少期", order: 8, text: "苦手な人はどんな人だったか？" },
    { id: "self-9", category: "自己分析", subCategory: "幼少期", order: 9, text: "周りからどんな人だと言われたか？" },
    { id: "self-10", category: "自己分析", subCategory: "幼少期", order: 10, text: "当時の自分の性格は？" },
    { id: "self-11", category: "自己分析", subCategory: "幼少期", order: 11, text: "自分の好きだった点は？" },
    { id: "self-12", category: "自己分析", subCategory: "幼少期", order: 12, text: "自分の嫌いだった点は？" },
    { id: "self-13", category: "自己分析", subCategory: "幼少期", order: 13, text: "当時、大切にしていたことは？" },
    { id: "self-14", category: "自己分析", subCategory: "幼少期", order: 14, text: "当時、おろそかにしていたことは？" },
    { id: "self-15", category: "自己分析", subCategory: "幼少期", order: 15, text: "自分の自慢できた点は？" },
    { id: "self-16", category: "自己分析", subCategory: "幼少期", order: 16, text: "当時のコンプレックスは？" },
    { id: "self-17", category: "自己分析", subCategory: "幼少期", order: 17, text: "人の言うことを聞くタイプだったか？" },
    { id: "self-18", category: "自己分析", subCategory: "幼少期", order: 18, text: "人とすぐ仲良くなれるタイプだったか？" },
    { id: "self-19", category: "自己分析", subCategory: "幼少期", order: 19, text: "人とぶつかることが多かったか？" },
    { id: "self-20", category: "自己分析", subCategory: "幼少期", order: 20, text: "どんなクセを持っていたか？" },
    { id: "self-21", category: "自己分析", subCategory: "幼少期", order: 21, text: "一番楽しかったできごとは？" },
    { id: "self-22", category: "自己分析", subCategory: "幼少期", order: 22, text: "一番嫌だったできごとは？" },
    { id: "self-23", category: "自己分析", subCategory: "幼少期", order: 23, text: "一番の成功体験は？" },
    { id: "self-24", category: "自己分析", subCategory: "幼少期", order: 24, text: "一番の失敗体験は？" },
    { id: "self-25", category: "自己分析", subCategory: "幼少期", order: 25, text: "一番恥ずかしかった経験は？" },
    { id: "self-26", category: "自己分析", subCategory: "幼少期", order: 26, text: "一番悲しかった経験は？" },
    { id: "self-27", category: "自己分析", subCategory: "幼少期", order: 27, text: "一番裏切られたと感じた経験は？" },
    { id: "self-28", category: "自己分析", subCategory: "幼少期", order: 28, text: "一番影響を受けた経験は？" },
    { id: "self-29", category: "自己分析", subCategory: "幼少期", order: 29, text: "一番後悔している経験は？" },
    { id: "self-30", category: "自己分析", subCategory: "幼少期", order: 30, text: "一番怒った経験は？" },
    { id: "self-31", category: "自己分析", subCategory: "幼少期", order: 31, text: "一番人に迷惑をかけた経験は？" },
    // --- 小学校 ---
    { id: "self-32", category: "自己分析", subCategory: "小学校", order: 32, text: "何をするのが好きだったか？" },
    { id: "self-33", category: "自己分析", subCategory: "小学校", order: 33, text: "何をするのが嫌いだったか？" },
    { id: "self-34", category: "自己分析", subCategory: "小学校", order: 34, text: "何が得意だったか？" },
    { id: "self-35", category: "自己分析", subCategory: "小学校", order: 35, text: "何が苦手だったか？" },
    { id: "self-36", category: "自己分析", subCategory: "小学校", order: 36, text: "当時の夢は？" },
    { id: "self-37", category: "自己分析", subCategory: "小学校", order: 37, text: "どんな友人が多かった？" },
    { id: "self-38", category: "自己分析", subCategory: "小学校", order: 38, text: "苦手な人はどんな人だったか？" },
    { id: "self-39", category: "自己分析", subCategory: "小学校", order: 39, text: "周りからどんな人だと言われたか？" },
    { id: "self-40", category: "自己分析", subCategory: "小学校", order: 40, text: "当時の自分の性格は？" },
    { id: "self-41", category: "自己分析", subCategory: "小学校", order: 41, text: "自分の好きだった点は？" },
    { id: "self-42", category: "自己分析", subCategory: "小学校", order: 42, text: "自分の嫌いだった点は？" },
    { id: "self-43", category: "自己分析", subCategory: "小学校", order: 43, text: "当時、大切にしていたことは？" },
    { id: "self-44", category: "自己分析", subCategory: "小学校", order: 44, text: "当時、おろそかにしていたことは？" },
    { id: "self-45", category: "自己分析", subCategory: "小学校", order: 45, text: "自分の自慢できた点は？" },
    { id: "self-46", category: "自己分析", subCategory: "小学校", order: 46, text: "当時のコンプレックスは？" },
    { id: "self-47", category: "自己分析", subCategory: "小学校", order: 47, text: "人の言うことを聞くタイプだったか？" },
    { id: "self-48", category: "自己分析", subCategory: "小学校", order: 48, text: "人とすぐ仲良くなれるタイプだったか？" },
    { id: "self-49", category: "自己分析", subCategory: "小学校", order: 49, text: "人とぶつかることが多かったか？" },
    { id: "self-50", category: "自己分析", subCategory: "小学校", order: 50, text: "どんなクセを持っていたか？" },
    { id: "self-51", category: "自己分析", subCategory: "小学校", order: 51, text: "一番楽しかったできごとは？" },
    { id: "self-52", category: "自己分析", subCategory: "小学校", order: 52, text: "一番嫌だったできごとは？" },
    { id: "self-53", category: "自己分析", subCategory: "小学校", order: 53, text: "一番の成功体験は？" },
    { id: "self-54", category: "自己分析", subCategory: "小学校", order: 54, text: "一番の失敗体験は？" },
    { id: "self-55", category: "自己分析", subCategory: "小学校", order: 55, text: "一番恥ずかしかった経験は？" },
    { id: "self-56", category: "自己分析", subCategory: "小学校", order: 56, text: "一番悲しかった経験は？" },
    { id: "self-57", category: "自己分析", subCategory: "小学校", order: 57, text: "一番裏切られたと感じた経験は？" },
    { id: "self-58", category: "自己分析", subCategory: "小学校", order: 58, text: "一番影響を受けた経験は？" },
    { id: "self-59", category: "自己分析", subCategory: "小学校", order: 59, text: "一番後悔している経験は？" },
    { id: "self-60", category: "自己分析", subCategory: "小学校", order: 60, text: "一番怒った経験は？" },
    { id: "self-61", category: "自己分析", subCategory: "小学校", order: 61, text: "一番人に迷惑をかけた経験は？" },
    // --- 中学校 ---
    { id: "self-62", category: "自己分析", subCategory: "中学校", order: 62, text: "何をするのが好きだったか？" },
    { id: "self-63", category: "自己分析", subCategory: "中学校", order: 63, text: "何をするのが嫌いだったか？" },
    { id: "self-64", category: "自己分析", subCategory: "中学校", order: 64, text: "何が得意だったか？" },
    { id: "self-65", category: "自己分析", subCategory: "中学校", order: 65, text: "何が苦手だったか？" },
    { id: "self-66", category: "自己分析", subCategory: "中学校", order: 66, text: "当時の夢は？" },
    { id: "self-67", category: "自己分析", subCategory: "中学校", order: 67, text: "どんな友人が多かった？" },
    { id: "self-68", category: "自己分析", subCategory: "中学校", order: 68, text: "苦手な人はどんな人だったか？" },
    { id: "self-69", category: "自己分析", subCategory: "中学校", order: 69, text: "周りからどんな人だと言われたか？" },
    { id: "self-70", category: "自己分析", subCategory: "中学校", order: 70, text: "当時の自分の性格は？" },
    { id: "self-71", category: "自己分析", subCategory: "中学校", order: 71, text: "自分の好きだった点は？" },
    { id: "self-72", category: "自己分析", subCategory: "中学校", order: 72, text: "自分の嫌いだった点は？" },
    { id: "self-73", category: "自己分析", subCategory: "中学校", order: 73, text: "当時、大切にしていたことは？" },
    { id: "self-74", category: "自己分析", subCategory: "中学校", order: 74, text: "当時、おろそかにしていたことは？" },
    { id: "self-75", category: "自己分析", subCategory: "中学校", order: 75, text: "自分の自慢できた点は？" },
    { id: "self-76", category: "自己分析", subCategory: "中学校", order: 76, text: "当時のコンプレックスは？" },
    { id: "self-77", category: "自己分析", subCategory: "中学校", order: 77, text: "人の言うことを聞くタイプだったか？" },
    { id: "self-78", category: "自己分析", subCategory: "中学校", order: 78, text: "人とすぐ仲良くなれるタイプだったか？" },
    { id: "self-79", category: "自己分析", subCategory: "中学校", order: 79, text: "人とぶつかることが多かったか？" },
    { id: "self-80", category: "自己分析", subCategory: "中学校", order: 80, text: "どんなクセを持っていたか？" },
    { id: "self-81", category: "自己分析", subCategory: "中学校", order: 81, text: "一番楽しかったできごとは？" },
    { id: "self-82", category: "自己分析", subCategory: "中学校", order: 82, text: "一番嫌だったできごとは？" },
    { id: "self-83", category: "自己分析", subCategory: "中学校", order: 83, text: "一番の成功体験は？" },
    { id: "self-84", category: "自己分析", subCategory: "中学校", order: 84, text: "一番の失敗体験は？" },
    { id: "self-85", category: "自己分析", subCategory: "中学校", order: 85, text: "一番恥ずかしかった経験は？" },
    { id: "self-86", category: "自己分析", subCategory: "中学校", order: 86, text: "一番悲しかった経験は？" },
    { id: "self-87", category: "自己分析", subCategory: "中学校", order: 87, text: "一番裏切られたと感じた経験は？" },
    { id: "self-88", category: "自己分析", subCategory: "中学校", order: 88, text: "一番影響を受けた経験は？" },
    { id: "self-89", category: "自己分析", subCategory: "中学校", order: 89, text: "一番後悔している経験は？" },
    { id: "self-90", category: "自己分析", subCategory: "中学校", order: 90, text: "一番怒った経験は？" },
    { id: "self-91", category: "自己分析", subCategory: "中学校", order: 91, text: "一番人に迷惑をかけた経験は？" },
    // --- 高校 ---
    { id: "self-92", category: "自己分析", subCategory: "高校", order: 92, text: "何をするのが好きだったか？" },
    { id: "self-93", category: "自己分析", subCategory: "高校", order: 93, text: "何をするのが嫌いだったか？" },
    { id: "self-94", category: "自己分析", subCategory: "高校", order: 94, text: "何が得意だったか？" },
    { id: "self-95", category: "自己分析", subCategory: "高校", order: 95, text: "何が苦手だったか？" },
    { id: "self-96", category: "自己分析", subCategory: "高校", order: 96, text: "当時の夢は？" },
    { id: "self-97", category: "自己分析", subCategory: "高校", order: 97, text: "どんな友人が多かった？" },
    { id: "self-98", category: "自己分析", subCategory: "高校", order: 98, text: "苦手な人はどんな人だったか？" },
    { id: "self-99", category: "自己分析", subCategory: "高校", order: 99, text: "周りからどんな人だと言われたか？" },
    { id: "self-100", category: "自己分析", subCategory: "高校", order: 100, text: "当時の自分の性格は？" },
    { id: "self-101", category: "自己分析", subCategory: "高校", order: 101, text: "自分の好きだった点は？" },
    { id: "self-102", category: "自己分析", subCategory: "高校", order: 102, text: "自分の嫌いだった点は？" },
    { id: "self-103", category: "自己分析", subCategory: "高校", order: 103, text: "当時、大切にしていたことは？" },
    { id: "self-104", category: "自己分析", subCategory: "高校", order: 104, text: "当時、おろそかにしていたことは？" },
    { id: "self-105", category: "自己分析", subCategory: "高校", order: 105, text: "自分の自慢できた点は？" },
    { id: "self-106", category: "自己分析", subCategory: "高校", order: 106, text: "当時のコンプレックスは？" },
    { id: "self-107", category: "自己分析", subCategory: "高校", order: 107, text: "人の言うことを聞くタイプだったか？" },
    { id: "self-108", category: "自己分析", subCategory: "高校", order: 108, text: "人とすぐ仲良くなれるタイプだったか？" },
    { id: "self-109", category: "自己分析", subCategory: "高校", order: 109, text: "人とぶつかることが多かったか？" },
    { id: "self-110", category: "自己分析", subCategory: "高校", order: 110, text: "どんなクセを持っていたか？" },
    { id: "self-111", category: "自己分析", subCategory: "高校", order: 111, text: "一番楽しかったできごとは？" },
    { id: "self-112", category: "自己分析", subCategory: "高校", order: 112, text: "一番嫌だったできごとは？" },
    { id: "self-113", category: "自己分析", subCategory: "高校", order: 113, text: "一番の成功体験は？" },
    { id: "self-114", category: "自己分析", subCategory: "高校", order: 114, text: "一番の失敗体験は？" },
    { id: "self-115", category: "自己分析", subCategory: "高校", order: 115, text: "一番恥ずかしかった経験は？" },
    { id: "self-116", category: "自己分析", subCategory: "高校", order: 116, text: "一番悲しかった経験は？" },
    { id: "self-117", category: "自己分析", subCategory: "高校", order: 117, text: "一番裏切られたと感じた経験は？" },
    { id: "self-118", category: "自己分析", subCategory: "高校", order: 118, text: "一番影響を受けた経験は？" },
    { id: "self-119", category: "自己分析", subCategory: "高校", order: 119, text: "一番後悔している経験は？" },
    { id: "self-120", category: "自己分析", subCategory: "高校", order: 120, text: "一番怒った経験は？" },
    { id: "self-121", category: "自己分析", subCategory: "高校", order: 121, text: "一番人に迷惑をかけた経験は？" },
    // --- 大学 ---
    { id: "self-122", category: "自己分析", subCategory: "大学", order: 122, text: "何をするのが好きだったか？" },
    { id: "self-123", category: "自己分析", subCategory: "大学", order: 123, text: "何をするのが嫌いだったか？" },
    { id: "self-124", category: "自己分析", subCategory: "大学", order: 124, text: "何が得意だったか？" },
    { id: "self-125", category: "自己分析", subCategory: "大学", order: 125, text: "何が苦手だったか？" },
    { id: "self-126", category: "自己分析", subCategory: "大学", order: 126, text: "当時の夢は？" },
    { id: "self-127", category: "自己分析", subCategory: "大学", order: 127, text: "どんな友人が多かった？" },
    { id: "self-128", category: "自己分析", subCategory: "大学", order: 128, text: "苦手な人はどんな人だったか？" },
    { id: "self-129", category: "自己分析", subCategory: "大学", order: 129, text: "周りからどんな人だと言われたか？" },
    { id: "self-130", category: "自己分析", subCategory: "大学", order: 130, text: "当時の自分の性格は？" },
    { id: "self-131", category: "自己分析", subCategory: "大学", order: 131, text: "自分の好きだった点は？" },
    { id: "self-132", category: "自己分析", subCategory: "大学", order: 132, text: "自分の嫌いだった点は？" },
    { id: "self-133", category: "自己分析", subCategory: "大学", order: 133, text: "当時、大切にしていたことは？" },
    { id: "self-134", category: "自己分析", subCategory: "大学", order: 134, text: "当時、おろそかにしていたことは？" },
    { id: "self-135", category: "自己分析", subCategory: "大学", order: 135, text: "自分の自慢できた点は？" },
    { id: "self-136", category: "自己分析", subCategory: "大学", order: 136, text: "当時のコンプレックスは？" },
    { id: "self-137", category: "自己分析", subCategory: "大学", order: 137, text: "人の言うことを聞くタイプだったか？" },
    { id: "self-138", category: "自己分析", subCategory: "大学", order: 138, text: "人とすぐ仲良くなれるタイプだったか？" },
    { id: "self-139", category: "自己分析", subCategory: "大学", order: 139, text: "人とぶつかることが多かったか？" },
    { id: "self-140", category: "自己分析", subCategory: "大学", order: 140, text: "どんなクセを持っていたか？" },
    { id: "self-141", category: "自己分析", subCategory: "大学", order: 141, text: "一番楽しかったできごとは？" },
    { id: "self-142", category: "自己分析", subCategory: "大学", order: 142, text: "一番嫌だったできごとは？" },
    { id: "self-143", category: "自己分析", subCategory: "大学", order: 143, text: "一番の成功体験は？" },
    { id: "self-144", category: "自己分析", subCategory: "大学", order: 144, text: "一番の失敗体験は？" },
    { id: "self-145", category: "自己分析", subCategory: "大学", order: 145, text: "一番恥ずかしかった経験は？" },
    { id: "self-146", category: "自己分析", subCategory: "大学", order: 146, text: "一番悲しかった経験は？" },
    { id: "self-147", category: "自己分析", subCategory: "大学", order: 147, text: "一番裏切られたと感じた経験は？" },
    { id: "self-148", category: "自己分析", subCategory: "大学", order: 148, text: "一番影響を受けた経験は？" },
    { id: "self-149", category: "自己分析", subCategory: "大学", order: 149, text: "一番後悔している経験は？" },
    { id: "self-150", category: "自己分析", subCategory: "大学", order: 150, text: "一番怒った経験は？" },
    { id: "self-151", category: "自己分析", subCategory: "大学", order: 151, text: "一番人に迷惑をかけた経験は？" },
    // --- 社会人（過去） ---
    { id: "self-152", category: "自己分析", subCategory: "社会人（過去）", order: 152, text: "何をするのが好きだったか？" },
    { id: "self-153", category: "自己分析", subCategory: "社会人（過去）", order: 153, text: "何をするのが嫌いだったか？" },
    { id: "self-154", category: "自己分析", subCategory: "社会人（過去）", order: 154, text: "何が得意だったか？" },
    { id: "self-155", category: "自己分析", subCategory: "社会人（過去）", order: 155, text: "何が苦手だったか？" },
    { id: "self-156", category: "自己分析", subCategory: "社会人（過去）", order: 156, text: "当時の夢は？" },
    { id: "self-157", category: "自己分析", subCategory: "社会人（過去）", order: 157, text: "どんな友人が多かった？" },
    { id: "self-158", category: "自己分析", subCategory: "社会人（過去）", order: 158, text: "苦手な人はどんな人だったか？" },
    { id: "self-159", category: "自己分析", subCategory: "社会人（過去）", order: 159, text: "周りからどんな人だと言われたか？" },
    { id: "self-160", category: "自己分析", subCategory: "社会人（過去）", order: 160, text: "当時の自分の性格は？" },
    { id: "self-161", category: "自己分析", subCategory: "社会人（過去）", order: 161, text: "自分の好きだった点は？" },
    { id: "self-162", category: "自己分析", subCategory: "社会人（過去）", order: 162, text: "自分の嫌いだった点は？" },
    { id: "self-163", category: "自己分析", subCategory: "社会人（過去）", order: 163, text: "当時、大切にしていたことは？" },
    { id: "self-164", category: "自己分析", subCategory: "社会人（過去）", order: 164, text: "当時、おろそかにしていたことは？" },
    { id: "self-165", category: "自己分析", subCategory: "社会人（過去）", order: 165, text: "自分の自慢できた点は？" },
    { id: "self-166", category: "自己分析", subCategory: "社会人（過去）", order: 166, text: "当時のコンプレックスは？" },
    { id: "self-167", category: "自己分析", subCategory: "社会人（過去）", order: 167, text: "人の言うことを聞くタイプだったか？" },
    { id: "self-168", category: "自己分析", subCategory: "社会人（過去）", order: 168, text: "人とすぐ仲良くなれるタイプだったか？" },
    { id: "self-169", category: "自己分析", subCategory: "社会人（過去）", order: 169, text: "人とぶつかることが多かったか？" },
    { id: "self-170", category: "自己分析", subCategory: "社会人（過去）", order: 170, text: "どんなクセを持っていたか？" },
    { id: "self-171", category: "自己分析", subCategory: "社会人（過去）", order: 171, text: "一番楽しかったできごとは？" },
    { id: "self-172", category: "自己分析", subCategory: "社会人（過去）", order: 172, text: "一番嫌だったできごとは？" },
    { id: "self-173", category: "自己分析", subCategory: "社会人（過去）", order: 173, text: "一番の成功体験は？" },
    { id: "self-174", category: "自己分析", subCategory: "社会人（過去）", order: 174, text: "一番の失敗体験は？" },
    { id: "self-175", category: "自己分析", subCategory: "社会人（過去）", order: 175, text: "一番恥ずかしかった経験は？" },
    { id: "self-176", category: "自己分析", subCategory: "社会人（過去）", order: 176, text: "一番悲しかった経験は？" },
    { id: "self-177", category: "自己分析", subCategory: "社会人（過去）", order: 177, text: "一番裏切られたと感じた経験は？" },
    { id: "self-178", category: "自己分析", subCategory: "社会人（過去）", order: 178, text: "一番影響を受けた経験は？" },
    { id: "self-179", category: "自己分析", subCategory: "社会人（過去）", order: 179, text: "一番後悔している経験は？" },
    { id: "self-180", category: "自己分析", subCategory: "社会人（過去）", order: 180, text: "一番怒った経験は？" },
    { id: "self-181", category: "自己分析", subCategory: "社会人（過去）", order: 181, text: "一番人に迷惑をかけた経験は？" },
    // --- 現在 ---
    { id: "self-182", category: "自己分析", subCategory: "現在", order: 182, text: "何をするのが好きか？" },
    { id: "self-183", category: "自己分析", subCategory: "現在", order: 183, text: "何をするのが嫌いか？" },
    { id: "self-184", category: "自己分析", subCategory: "現在", order: 184, text: "何が得意か？" },
    { id: "self-185", category: "自己分析", subCategory: "現在", order: 185, text: "何が苦手か？" },
    { id: "self-186", category: "自己分析", subCategory: "現在", order: 186, text: "夢は？" },
    { id: "self-187", category: "自己分析", subCategory: "現在", order: 187, text: "どんな友人が多いか？" },
    { id: "self-188", category: "自己分析", subCategory: "現在", order: 188, text: "苦手な人はどんな人か？" },
    { id: "self-189", category: "自己分析", subCategory: "現在", order: 189, text: "周りからどんな人だと言われるか？" },
    { id: "self-190", category: "自己分析", subCategory: "現在", order: 190, text: "今の自分の性格は？" },
    { id: "self-191", category: "自己分析", subCategory: "現在", order: 191, text: "自分の好きな点は？" },
    { id: "self-192", category: "自己分析", subCategory: "現在", order: 192, text: "自分の嫌いな点は？" },
    { id: "self-193", category: "自己分析", subCategory: "現在", order: 193, text: "大切にしていることは？" },
    { id: "self-194", category: "自己分析", subCategory: "現在", order: 194, text: "おろそかにしていることは？" },
    { id: "self-195", category: "自己分析", subCategory: "現在", order: 195, text: "自分の自慢できる点は？" },
    { id: "self-196", category: "自己分析", subCategory: "現在", order: 196, text: "コンプレックスは？" },
    { id: "self-197", category: "自己分析", subCategory: "現在", order: 197, text: "人の言うことを聞くタイプか？" },
    { id: "self-198", category: "自己分析", subCategory: "現在", order: 198, text: "人とすぐ仲良くなれるタイプか？" },
    { id: "self-199", category: "自己分析", subCategory: "現在", order: 199, text: "人とぶつかることが多いか？" },
    { id: "self-200", category: "自己分析", subCategory: "現在", order: 200, text: "どんなクセを持っているか？" },
    // ===== 勉強 =====
    // --- 導入・小学校 ---
    { id: "study-1", category: "勉強", subCategory: "導入・小学校", order: 1, text: "そもそもなぜ勉強のことを考えるべきか？" },
    { id: "study-2", category: "勉強", subCategory: "導入・小学校", order: 2, text: "好きだった教科は？" },
    { id: "study-3", category: "勉強", subCategory: "導入・小学校", order: 3, text: "嫌いだった教科は？" },
    { id: "study-4", category: "勉強", subCategory: "導入・小学校", order: 4, text: "勉強で成功した経験は？" },
    { id: "study-5", category: "勉強", subCategory: "導入・小学校", order: 5, text: "勉強で挫折した経験は？" },
    { id: "study-6", category: "勉強", subCategory: "導入・小学校", order: 6, text: "勉強で何を得たか？" },
    { id: "study-7", category: "勉強", subCategory: "導入・小学校", order: 7, text: "なぜその部活に入っていた？" },
    { id: "study-8", category: "勉強", subCategory: "導入・小学校", order: 8, text: "部活で成功した経験は？" },
    { id: "study-9", category: "勉強", subCategory: "導入・小学校", order: 9, text: "部活で挫折した経験は？" },
    { id: "study-10", category: "勉強", subCategory: "導入・小学校", order: 10, text: "部活で何を得たか？" },
    // --- 中学校 ---
    { id: "study-11", category: "勉強", subCategory: "中学校", order: 11, text: "好きだった教科は？" },
    { id: "study-12", category: "勉強", subCategory: "中学校", order: 12, text: "嫌いだった教科は？" },
    { id: "study-13", category: "勉強", subCategory: "中学校", order: 13, text: "勉強で成功した経験は？" },
    { id: "study-14", category: "勉強", subCategory: "中学校", order: 14, text: "勉強で挫折した経験は？" },
    { id: "study-15", category: "勉強", subCategory: "中学校", order: 15, text: "勉強で何を得たか？" },
    { id: "study-16", category: "勉強", subCategory: "中学校", order: 16, text: "なぜその部活に入っていた？" },
    { id: "study-17", category: "勉強", subCategory: "中学校", order: 17, text: "部活で成功した経験は？" },
    { id: "study-18", category: "勉強", subCategory: "中学校", order: 18, text: "部活で挫折した経験は？" },
    { id: "study-19", category: "勉強", subCategory: "中学校", order: 19, text: "部活で何を得たか？" },
    // --- 高校 ---
    { id: "study-20", category: "勉強", subCategory: "高校", order: 20, text: "好きだった教科は？" },
    { id: "study-21", category: "勉強", subCategory: "高校", order: 21, text: "嫌いだった教科は？" },
    { id: "study-22", category: "勉強", subCategory: "高校", order: 22, text: "勉強で成功した経験は？" },
    { id: "study-23", category: "勉強", subCategory: "高校", order: 23, text: "勉強で挫折した経験は？" },
    { id: "study-24", category: "勉強", subCategory: "高校", order: 24, text: "勉強で何を得たか？" },
    { id: "study-25", category: "勉強", subCategory: "高校", order: 25, text: "なぜその部活に入っていた？" },
    { id: "study-26", category: "勉強", subCategory: "高校", order: 26, text: "部活で成功した経験は？" },
    { id: "study-27", category: "勉強", subCategory: "高校", order: 27, text: "部活で挫折した経験は？" },
    { id: "study-28", category: "勉強", subCategory: "高校", order: 28, text: "部活で何を得たか？" },
    // --- 大学 ---
    { id: "study-29", category: "勉強", subCategory: "大学", order: 29, text: "好きだった教科は？" },
    { id: "study-30", category: "勉強", subCategory: "大学", order: 30, text: "嫌いだった教科は？" },
    { id: "study-31", category: "勉強", subCategory: "大学", order: 31, text: "勉強で成功した経験は？" },
    { id: "study-32", category: "勉強", subCategory: "大学", order: 32, text: "勉強で挫折した経験は？" },
    { id: "study-33", category: "勉強", subCategory: "大学", order: 33, text: "勉強で何を得たか？" },
    { id: "study-34", category: "勉強", subCategory: "大学", order: 34, text: "なぜその部活に入っていた？" },
    { id: "study-35", category: "勉強", subCategory: "大学", order: 35, text: "部活で成功した経験は？" },
    { id: "study-36", category: "勉強", subCategory: "大学", order: 36, text: "部活で挫折した経験は？" },
    { id: "study-37", category: "勉強", subCategory: "大学", order: 37, text: "部活で何を得たか？" },
    // --- 社会人（過去） ---
    { id: "study-38", category: "勉強", subCategory: "社会人（過去）", order: 38, text: "どんな勉強が好きだったか？" },
    { id: "study-39", category: "勉強", subCategory: "社会人（過去）", order: 39, text: "どんな勉強が嫌いだったか？" },
    { id: "study-40", category: "勉強", subCategory: "社会人（過去）", order: 40, text: "勉強で成功した経験は？" },
    { id: "study-41", category: "勉強", subCategory: "社会人（過去）", order: 41, text: "勉強で挫折した経験は？" },
    { id: "study-42", category: "勉強", subCategory: "社会人（過去）", order: 42, text: "勉強で何を得たか？" },
    // --- 現在 ---
    { id: "study-43", category: "勉強", subCategory: "現在", order: 43, text: "なぜ勉強するのか？" },
    { id: "study-44", category: "勉強", subCategory: "現在", order: 44, text: "どんな勉強が好きか？" },
    { id: "study-45", category: "勉強", subCategory: "現在", order: 45, text: "どんな勉強が嫌いか？" },
    { id: "study-46", category: "勉強", subCategory: "現在", order: 46, text: "今一番勉強したいことは？" },
    { id: "study-47", category: "勉強", subCategory: "現在", order: 47, text: "人生で一番勉強で嬉しかったことは？" },
    { id: "study-48", category: "勉強", subCategory: "現在", order: 48, text: "人生で一番勉強で悲しかったことは？" },
    { id: "study-49", category: "勉強", subCategory: "現在", order: 49, text: "勉強がはかどるコツは？" },
    { id: "study-50", category: "勉強", subCategory: "現在", order: 50, text: "勉強のやる気をどう上げるか？" },
    // ===== 仕事 =====
    // --- 仕事全般 ---
    { id: "work-1", category: "仕事", subCategory: "仕事全般", order: 1, text: "そもそもなぜ仕事のことを考えるべきか？" },
    { id: "work-2", category: "仕事", subCategory: "仕事全般", order: 2, text: "今の自分の課題点は何か？" },
    { id: "work-3", category: "仕事", subCategory: "仕事全般", order: 3, text: "「仕事ができる」とは何か？" },
    { id: "work-4", category: "仕事", subCategory: "仕事全般", order: 4, text: "どうしたらもっと仕事ができるようになるか？" },
    { id: "work-5", category: "仕事", subCategory: "仕事全般", order: 5, text: "どんな人を「仕事ができる人」だと思うか？" },
    { id: "work-6", category: "仕事", subCategory: "仕事全般", order: 6, text: "どうしたら収入を増やせるか？" },
    { id: "work-7", category: "仕事", subCategory: "仕事全般", order: 7, text: "○○さんはなぜ仕事ができるのか？" },
    { id: "work-8", category: "仕事", subCategory: "仕事全般", order: 8, text: "○○さんはなぜ仕事ができないのか？" },
    { id: "work-9", category: "仕事", subCategory: "仕事全般", order: 9, text: "どういうとき、自分は成長できるか？" },
    { id: "work-10", category: "仕事", subCategory: "仕事全般", order: 10, text: "仕事で成功した経験は？" },
    { id: "work-11", category: "仕事", subCategory: "仕事全般", order: 11, text: "仕事で失敗した経験は？" },
    { id: "work-12", category: "仕事", subCategory: "仕事全般", order: 12, text: "仕事で挫折した経験は？" },
    // --- 業務 ---
    { id: "work-13", category: "仕事", subCategory: "業務", order: 13, text: "どうしたら仕事のスピードが速くなるか？" },
    { id: "work-14", category: "仕事", subCategory: "業務", order: 14, text: "どうしたら仕事の質を上げられるか？" },
    { id: "work-15", category: "仕事", subCategory: "業務", order: 15, text: "どうしたら集中力を上げられるか？" },
    { id: "work-16", category: "仕事", subCategory: "業務", order: 16, text: "社外メールで意識することは？" },
    { id: "work-17", category: "仕事", subCategory: "業務", order: 17, text: "社内メールで意識することは？" },
    { id: "work-18", category: "仕事", subCategory: "業務", order: 18, text: "どんなタスク管理をするべきか？" },
    // --- 会議 ---
    { id: "work-19", category: "仕事", subCategory: "会議", order: 19, text: "意味のある会議にするには？" },
    { id: "work-20", category: "仕事", subCategory: "会議", order: 20, text: "どうしたらみんな発言できるか？" },
    { id: "work-21", category: "仕事", subCategory: "会議", order: 21, text: "どんな意見を言うべきか？" },
    { id: "work-22", category: "仕事", subCategory: "会議", order: 22, text: "○○さんの話をどう思ったか？" },
    { id: "work-23", category: "仕事", subCategory: "会議", order: 23, text: "意見が違うときはどうするか？" },
    // --- チーム ---
    { id: "work-24", category: "仕事", subCategory: "チーム", order: 24, text: "チームで動く上で大事なことは？" },
    { id: "work-25", category: "仕事", subCategory: "チーム", order: 25, text: "どうしたらチームが機能するか？" },
    { id: "work-26", category: "仕事", subCategory: "チーム", order: 26, text: "自分の役割は何か？" },
    { id: "work-27", category: "仕事", subCategory: "チーム", order: 27, text: "どうしたらチームに貢献できるか？" },
    { id: "work-28", category: "仕事", subCategory: "チーム", order: 28, text: "チームメンバーの役割は何か？" },
    { id: "work-29", category: "仕事", subCategory: "チーム", order: 29, text: "仕事以外でもメンバーと関わるべきか？" },
    // --- マネジメント ---
    { id: "work-30", category: "仕事", subCategory: "マネジメント", order: 30, text: "マネジメントで大事なことは？" },
    { id: "work-31", category: "仕事", subCategory: "マネジメント", order: 31, text: "自分は何をやるべきか？" },
    { id: "work-32", category: "仕事", subCategory: "マネジメント", order: 32, text: "自分は何をやらないべきか？" },
    { id: "work-33", category: "仕事", subCategory: "マネジメント", order: 33, text: "部下とはどう関わるべきか？" },
    { id: "work-34", category: "仕事", subCategory: "マネジメント", order: 34, text: "部下のパフォーマンスを高めるには？" },
    { id: "work-35", category: "仕事", subCategory: "マネジメント", order: 35, text: "他部署とはどう関わるべきか？" },
    { id: "work-36", category: "仕事", subCategory: "マネジメント", order: 36, text: "他部署との意見が違うときはどうするべきか？" },
    // --- 商談 ---
    { id: "work-37", category: "仕事", subCategory: "商談", order: 37, text: "どんな準備をするべきか？" },
    { id: "work-38", category: "仕事", subCategory: "商談", order: 38, text: "見た目にはどう気をつけるべきか？" },
    { id: "work-39", category: "仕事", subCategory: "商談", order: 39, text: "どんな資料がよいか？" },
    { id: "work-40", category: "仕事", subCategory: "商談", order: 40, text: "最初はどんな話をするべきか？" },
    { id: "work-41", category: "仕事", subCategory: "商談", order: 41, text: "全体としてどんな話をするべきか？" },
    { id: "work-42", category: "仕事", subCategory: "商談", order: 42, text: "質疑・応答で意識することは？" },
    { id: "work-43", category: "仕事", subCategory: "商談", order: 43, text: "最後に意識することは？" },
    { id: "work-44", category: "仕事", subCategory: "商談", order: 44, text: "どうしたら成約率を上げられるか？" },
    { id: "work-45", category: "仕事", subCategory: "商談", order: 45, text: "話し方のコツはあるか？" },
    { id: "work-46", category: "仕事", subCategory: "商談", order: 46, text: "商談がうまい人はどんな特徴があるか？" },
    // --- プレゼン ---
    { id: "work-47", category: "仕事", subCategory: "プレゼン", order: 47, text: "どんな準備をするべきか？" },
    { id: "work-48", category: "仕事", subCategory: "プレゼン", order: 48, text: "どんなプレゼン資料にするべきか？" },
    { id: "work-49", category: "仕事", subCategory: "プレゼン", order: 49, text: "最初はどんな話をするべきか？" },
    { id: "work-50", category: "仕事", subCategory: "プレゼン", order: 50, text: "全体としてどんな話をするべきか？" },
    { id: "work-51", category: "仕事", subCategory: "プレゼン", order: 51, text: "質疑・応答で意識することは？" },
    { id: "work-52", category: "仕事", subCategory: "プレゼン", order: 52, text: "最後に意識することは？" },
    { id: "work-53", category: "仕事", subCategory: "プレゼン", order: 53, text: "話し方のコツはあるか？" },
    { id: "work-54", category: "仕事", subCategory: "プレゼン", order: 54, text: "プレゼンがうまい人はどんな特徴があるか？" },
    // --- 企画書 ---
    { id: "work-55", category: "仕事", subCategory: "企画書", order: 55, text: "どんな内容にするべきか？" },
    { id: "work-56", category: "仕事", subCategory: "企画書", order: 56, text: "訴求ポイントは何にするべきか？" },
    { id: "work-57", category: "仕事", subCategory: "企画書", order: 57, text: "全体として意識することは？" },
    { id: "work-58", category: "仕事", subCategory: "企画書", order: 58, text: "誰に向けた企画にするべきか？" },
    { id: "work-59", category: "仕事", subCategory: "企画書", order: 59, text: "見出しで意識することは？" },
    { id: "work-60", category: "仕事", subCategory: "企画書", order: 60, text: "企画を量産するにはどうするべきか？" },
    { id: "work-61", category: "仕事", subCategory: "企画書", order: 61, text: "どうしても思いつかないときの対処法は？" },
    { id: "work-62", category: "仕事", subCategory: "企画書", order: 62, text: "どうすれば流行に敏感になれるか？" },
    { id: "work-63", category: "仕事", subCategory: "企画書", order: 63, text: "企画書のビジュアルはどうあるべきか？" },
    { id: "work-64", category: "仕事", subCategory: "企画書", order: 64, text: "企画書を早く作るにはどうするべきか？" },
    // --- トラブル対応 ---
    { id: "work-65", category: "仕事", subCategory: "トラブル対応", order: 65, text: "なぜトラブルが起こったか？" },
    { id: "work-66", category: "仕事", subCategory: "トラブル対応", order: 66, text: "トラブルにどう対応するか？" },
    { id: "work-67", category: "仕事", subCategory: "トラブル対応", order: 67, text: "相手はなぜ怒っていると思うか？" },
    { id: "work-68", category: "仕事", subCategory: "トラブル対応", order: 68, text: "話し方にコツはあるか？" },
    { id: "work-69", category: "仕事", subCategory: "トラブル対応", order: 69, text: "上司への説明のポイントは？" },
    // --- 人間関係 ---
    { id: "work-70", category: "仕事", subCategory: "人間関係", order: 70, text: "上司とどう関わるべきか？" },
    { id: "work-71", category: "仕事", subCategory: "人間関係", order: 71, text: "部下とどう関わるべきか？" },
    { id: "work-72", category: "仕事", subCategory: "人間関係", order: 72, text: "同僚とどう関わるべきか？" },
    { id: "work-73", category: "仕事", subCategory: "人間関係", order: 73, text: "他部署の人とどう関わるべきか？" },
    { id: "work-74", category: "仕事", subCategory: "人間関係", order: 74, text: "苦手な人とどう接するべきか？" },
    // --- ホウレンソウ ---
    { id: "work-75", category: "仕事", subCategory: "ホウレンソウ", order: 75, text: "報告で大事なことは？" },
    { id: "work-76", category: "仕事", subCategory: "ホウレンソウ", order: 76, text: "連絡で大事なことは？" },
    { id: "work-77", category: "仕事", subCategory: "ホウレンソウ", order: 77, text: "相談で大事なことは？" },
    { id: "work-78", category: "仕事", subCategory: "ホウレンソウ", order: 78, text: "ホウレンソウで大事なことは？" },
    { id: "work-79", category: "仕事", subCategory: "ホウレンソウ", order: 79, text: "話し方のコツはあるか？" },
    // --- 転職 ---
    { id: "work-80", category: "仕事", subCategory: "転職", order: 80, text: "なぜその業界を志望するのか？" },
    { id: "work-81", category: "仕事", subCategory: "転職", order: 81, text: "なぜその職種を志望するのか？" },
    { id: "work-82", category: "仕事", subCategory: "転職", order: 82, text: "自分のやりたいことは何か？" },
    { id: "work-83", category: "仕事", subCategory: "転職", order: 83, text: "これまでの会社にはなぜ入ったのか？" },
    { id: "work-84", category: "仕事", subCategory: "転職", order: 84, text: "なぜ今の会社に入ったのか？" },
    { id: "work-85", category: "仕事", subCategory: "転職", order: 85, text: "なぜ今、その会社を志望するのか？" },
    { id: "work-86", category: "仕事", subCategory: "転職", order: 86, text: "仕事しながら転職活動をするには？" },
    { id: "work-87", category: "仕事", subCategory: "転職", order: 87, text: "どんな社会課題を解決したいか？" },
    { id: "work-88", category: "仕事", subCategory: "転職", order: 88, text: "面接では何を話すべきか？" },
    // --- メンタル管理 ---
    { id: "work-89", category: "仕事", subCategory: "メンタル管理", order: 89, text: "なぜ気分が悪いのか？" },
    { id: "work-90", category: "仕事", subCategory: "メンタル管理", order: 90, text: "どういうときに気分がいいか？" },
    { id: "work-91", category: "仕事", subCategory: "メンタル管理", order: 91, text: "どういうときに気分が悪くなりやすいか？" },
    { id: "work-92", category: "仕事", subCategory: "メンタル管理", order: 92, text: "どうしたら気分よくいられるか？" },
    { id: "work-93", category: "仕事", subCategory: "メンタル管理", order: 93, text: "マイナス思考な人をどう思うか？" },
    { id: "work-94", category: "仕事", subCategory: "メンタル管理", order: 94, text: "なぜ緊張してしまうのか？" },
    { id: "work-95", category: "仕事", subCategory: "メンタル管理", order: 95, text: "人前で緊張しないにはどうしたらいいか？" },
    // --- 情報収集 ---
    { id: "work-96", category: "仕事", subCategory: "情報収集", order: 96, text: "なぜ情報収集が必要か？" },
    { id: "work-97", category: "仕事", subCategory: "情報収集", order: 97, text: "情報収集するベストな方法は？" },
    { id: "work-98", category: "仕事", subCategory: "情報収集", order: 98, text: "情報収集がうまい人はどうやっているのか？" },
    { id: "work-99", category: "仕事", subCategory: "情報収集", order: 99, text: "情報ソースはどこがいいか？" },
    { id: "work-100", category: "仕事", subCategory: "情報収集", order: 100, text: "いつ情報収集をするべきか？" },
];

// 既存コードとの後方互換（ランダム抽出用）
export const PREDEFINED_THEMES = QUESTIONS.map((q) => q.text);

export const FEATURED_THEMES = [
    "1年後、どんな人間になっていたいか？",
    "「仕事ができる」とは何か？",
    "自分の好きな点は？",
];
